fig, axs = plt.subplots(2, 2)
axs[0, 0].plot(steps, x1)
axs[0, 0].set_title('Axis [0, 0]')
axs[0, 1].plot(steps, x1, 'tab:orange')
axs[0, 1].set_title('Axis [0, 1]')
axs[1, 0].plot(steps, x1, 'tab:green')
axs[1, 0].set_title('Axis [1, 0]')
axs[1, 1].plot(steps,x1, 'tab:red')
axs[1, 1].set_title('Axis [1, 1]')

    #print(mnk(length, data[i]))
#ax.legend("4325")
# plt.xlabel("Шаг")
# plt.ylabel("Ошибка")
# plt.grid(True)
# plt.show()
plt.show()